// <auto-generated />
using System;
using ChargeMaster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChargeMaster.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314103313_AddDaikinSessionsTable")]
    partial class AddDaikinSessionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChargeMaster.Data.ChargeSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChargeLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ChargeState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ChargeTarget")
                        .HasColumnType("integer");

                    b.Property<long?>("SessionEnergy")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionStartTime")
                        .HasColumnType("bigint");

                    b.Property<long?>("SessionStartValue")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionStartTime")
                        .IsDescending();

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("ChargeSessions");
                });

            modelBuilder.Entity("ChargeMaster.Data.DaikinSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("ArbetsrumTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("HallTemperature")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsHeating")
                        .HasColumnType("boolean");

                    b.Property<double?>("SovrumTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetTemperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("DaikinSessions");
                });

            modelBuilder.Entity("ChargeMaster.Data.ElectricityPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EurPerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("EUR_per_kWh");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("EXR");

                    b.Property<decimal>("SekPerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("SEK_per_kWh");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("time_end");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("time_start");

                    b.HasKey("Id");

                    b.ToTable("ElectricityPrices");
                });

            modelBuilder.Entity("ChargeMaster.Data.ShellyTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ShellyTemperatures");
                });

            modelBuilder.Entity("ChargeMaster.Data.WallboxMeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AccEnergy")
                        .HasColumnType("bigint");

                    b.Property<long>("ApparentPower")
                        .HasColumnType("bigint");

                    b.Property<string>("MeterSerial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("WallboxMeterReadings");
                });

            modelBuilder.Entity("ChargeMaster.Services.SMHI.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CloudCoverage")
                        .HasColumnType("double precision");

                    b.Property<int?>("Luftfuktighet")
                        .HasColumnType("integer");

                    b.Property<double?>("Lufttryck")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxPrecipitation")
                        .HasColumnType("double precision");

                    b.Property<double?>("MeanPrecipitation")
                        .HasColumnType("double precision");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<int?>("PrecipitationCategory")
                        .HasColumnType("integer");

                    b.Property<double?>("PrecipitationMedian")
                        .HasColumnType("double precision");

                    b.Property<int?>("PrecipitationProbability")
                        .HasColumnType("integer");

                    b.Property<double?>("Sikt")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<int?>("ThunderstormProbability")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("TotalPrecipitation")
                        .HasColumnType("double precision");

                    b.Property<int?>("WeatherSymbol")
                        .HasColumnType("integer");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<double?>("WindGust")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Time")
                        .IsUnique();

                    b.ToTable("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
