// <auto-generated />
using System;
using ChargeMaster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChargeMaster.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChargeMaster.Data.ShellyTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ShellyTemperatures");
                });

            modelBuilder.Entity("ChargeMaster.Services.ElectricityPrice.ElectricityPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EurPerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("EUR_per_kWh");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("EXR");

                    b.Property<decimal>("SekPerKwh")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("SEK_per_kWh");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("time_end");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp without time zone")
                        .HasJsonPropertyName("time_start");

                    b.HasKey("Id");

                    b.ToTable("ElectricityPrices");
                });

            modelBuilder.Entity("ChargeMaster.Services.Wallbox.WallboxMeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AccEnergy")
                        .HasColumnType("bigint");

                    b.Property<long>("ApparentPower")
                        .HasColumnType("bigint");

                    b.Property<string>("MeterSerial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("WallboxMeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
