-- SQL-script för att skapa ShellyTemperature-tabellen i PostgreSQL 17
-- Används när migrations inte kan köras i produktionsmiljö

-- Skapa tabellen
CREATE TABLE IF NOT EXISTS public."ShellyTemperature"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DeviceId" text NOT NULL,
    "TemperatureCelsius" double precision NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ShellyTemperature" PRIMARY KEY ("Id")
);

-- Skapa index för effektiv sökning på (DeviceId, Timestamp DESC)
-- Detta är användbart för att hitta senaste temperaturvärden per enhet
CREATE INDEX IF NOT EXISTS "IX_ShellyTemperature_DeviceId_Timestamp" 
ON public."ShellyTemperature" ("DeviceId" ASC, "Timestamp" DESC);

-- Skapa index på DeviceId för snabb filtrering
CREATE INDEX IF NOT EXISTS "IX_ShellyTemperature_DeviceId" 
ON public."ShellyTemperature" ("DeviceId");

-- Skapa index på Timestamp för tidsbaserad sortering
CREATE INDEX IF NOT EXISTS "IX_ShellyTemperature_Timestamp" 
ON public."ShellyTemperature" ("Timestamp" DESC);

-- Sätt upp table comment för dokumentation
COMMENT ON TABLE public."ShellyTemperature" IS 
'Lagrar temperaturmätningar från Shelly-enheter. Rekommenderas att rensa gamla poster regelbundet.';

COMMENT ON COLUMN public."ShellyTemperature"."DeviceId" IS 
'ID för Shelly-enheten (sovrum, hall, arbetsrum)';

COMMENT ON COLUMN public."ShellyTemperature"."TemperatureCelsius" IS 
'Temperaturen i Celsius';

COMMENT ON COLUMN public."ShellyTemperature"."Timestamp" IS 
'Tidpunkten då temperaturen mättes';
