-- Create DaikinSessions table for storing heat pump session data
-- This table stores settings sent to the Daikin heat pump along with 
-- measured temperature values from Shelly devices and current electricity price

CREATE TABLE "DaikinSessions" (
    "Id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "TargetTemperature" double precision NOT NULL,
    "IsHeating" boolean NOT NULL,
    "ArbetsrumTemperature" double precision,
    "HallTemperature" double precision,
    "SovrumTemperature" double precision,
    "CurrentPrice" numeric(18,2)
);

-- Create index on Timestamp column for efficient time-based queries
CREATE INDEX "IX_DaikinSessions_Timestamp" 
ON "DaikinSessions" ("Timestamp" DESC);

-- Add comments for documentation
COMMENT ON TABLE "DaikinSessions" IS 'Stores Daikin heat pump session data including target temperature and heating/cooling mode, along with measured temperatures from Shelly devices and current electricity price';
COMMENT ON COLUMN "DaikinSessions"."Id" IS 'Unique identifier for the session record';
COMMENT ON COLUMN "DaikinSessions"."Timestamp" IS 'When the session data was recorded';
COMMENT ON COLUMN "DaikinSessions"."TargetTemperature" IS 'Target temperature set on the Daikin heat pump in °C';
COMMENT ON COLUMN "DaikinSessions"."IsHeating" IS 'True for heating mode, false for cooling mode';
COMMENT ON COLUMN "DaikinSessions"."ArbetsrumTemperature" IS 'Temperature measured in the office room (arbetsrum) in °C';
COMMENT ON COLUMN "DaikinSessions"."HallTemperature" IS 'Temperature measured in the hallway (hall) in °C';
COMMENT ON COLUMN "DaikinSessions"."SovrumTemperature" IS 'Temperature measured in the bedroom (sovrum) in °C';
COMMENT ON COLUMN "DaikinSessions"."CurrentPrice" IS 'Current electricity price in SEK per kWh';

-- Skapa i produktion:
-- GRANT ALL PRIVILEGES ON TABLE "DaikinSessions" TO chargemaster;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO chargemaster;