-- SQL-script för att skapa ElectricityPrices-tabellen i PostgreSQL 17
-- Används när migrations inte kan köras i produktionsmiljö

-- Skapa tabellen
CREATE TABLE IF NOT EXISTS public."ElectricityPrices"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SekPerKwh" numeric(18, 2) NOT NULL,
    "EurPerKwh" numeric(18, 2) NOT NULL,
    "ExchangeRate" numeric(18, 2) NOT NULL,
    "TimeStart" timestamp without time zone NOT NULL,
    "TimeEnd" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ElectricityPrices" PRIMARY KEY ("Id")
);

-- Skapa index på TimeStart för snabb sökning av priser för specifik tid
CREATE INDEX IF NOT EXISTS "IX_ElectricityPrices_TimeStart" 
ON public."ElectricityPrices" ("TimeStart" DESC);

-- Skapa index på TimeEnd för sökning av pris-perioder
CREATE INDEX IF NOT EXISTS "IX_ElectricityPrices_TimeEnd" 
ON public."ElectricityPrices" ("TimeEnd" DESC);

-- Skapa composite index för att hitta prisperioder för ett specifikt tidsintervall
CREATE INDEX IF NOT EXISTS "IX_ElectricityPrices_TimeStart_TimeEnd" 
ON public."ElectricityPrices" ("TimeStart" ASC, "TimeEnd" ASC);

-- Sätt upp table comment för dokumentation
COMMENT ON TABLE public."ElectricityPrices" IS 
'Lagrar elpriser från API:et. Innehåller priser i både SEK och EUR med växelkurs.';

COMMENT ON COLUMN public."ElectricityPrices"."SekPerKwh" IS 
'Elpris i SEK per kWh med 2 decimaler';

COMMENT ON COLUMN public."ElectricityPrices"."EurPerKwh" IS 
'Elpris i EUR per kWh med 2 decimaler';

COMMENT ON COLUMN public."ElectricityPrices"."ExchangeRate" IS 
'Växelkurs SEK/EUR som användes vid konvertering';

COMMENT ON COLUMN public."ElectricityPrices"."TimeStart" IS 
'Starttid för prisperioden (UTC)';

COMMENT ON COLUMN public."ElectricityPrices"."TimeEnd" IS 
'Sluttid för prisperioden (UTC)';
