-- SQL-script för att skapa ChargeSession-tabellen i PostgreSQL 17
-- Används när migrations inte kan köras i produktionsmiljö

-- Skapa tabellen
CREATE TABLE IF NOT EXISTS public."ChargeSession"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "SessionEnergy" bigint NULL,
    "SessionStartValue" bigint NULL,
    "SessionStartTime" bigint NULL,
    "ChargeLevel" integer NULL,
    "ChargeTarget" integer NULL,
    "ChargeState" character varying(20) NOT NULL,
    CONSTRAINT "PK_ChargeSession" PRIMARY KEY ("Id")
);

-- Skapa index på SessionStartTime för att hitta sessioner efter start-tid
CREATE INDEX IF NOT EXISTS "IX_ChargeSession_SessionStartTime" 
ON public."ChargeSession" ("SessionStartTime" DESC);

-- Skapa index på Timestamp för tidsbaserad sortering
CREATE INDEX IF NOT EXISTS "IX_ChargeSession_Timestamp" 
ON public."ChargeSession" ("Timestamp" DESC);

-- Sätt upp table comment för dokumentation
COMMENT ON TABLE public."ChargeSession" IS 
'Lagrar laddningssessiondata från Wallbox-laddaren. Innehåller information om varje laddningssession.';

COMMENT ON COLUMN public."ChargeSession"."Timestamp" IS 
'Tidpunkten då sessionsdata spelades in';

COMMENT ON COLUMN public."ChargeSession"."SessionEnergy" IS 
'Energi förbrukad under sessionen i Wh (Watt-timmar)';

COMMENT ON COLUMN public."ChargeSession"."SessionStartValue" IS 
'Startvärde för energi i Wh när sessionen började';

COMMENT ON COLUMN public."ChargeSession"."SessionStartTime" IS 
'Unix timestamp (sekunder) när laddningssessionen startade';

COMMENT ON COLUMN public."ChargeSession"."ChargeLevel" IS 
'Aktuell laddningsnivå i procent (0-100)';

COMMENT ON COLUMN public."ChargeSession"."ChargeTarget" IS 
'Målnivå för laddning i procent (0-100)';

COMMENT ON COLUMN public."ChargeSession"."ChargeState" IS 
'Aktuell status för laddningssessionen (CHARGING, IDLE, FINISHED, osv.) - Max 20 tecken';
