-- SQL-script för att skapa WallboxMeterReadings-tabellen i PostgreSQL 17
-- Används när migrations inte kan köras i produktionsmiljö

-- Skapa tabellen
CREATE TABLE IF NOT EXISTS public."WallboxMeterReadings"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ReadAt" timestamp without time zone NOT NULL,
    "RawJson" character varying(1000) NOT NULL,
    "AccEnergy" bigint NOT NULL,
    "MeterSerial" character varying(100) NULL,
    "ApparentPower" bigint NOT NULL,
    CONSTRAINT "PK_WallboxMeterReadings" PRIMARY KEY ("Id")
);

-- Skapa index på ReadAt för snabb sökning av mätningar över tid
CREATE INDEX IF NOT EXISTS "IX_WallboxMeterReadings_ReadAt" 
ON public."WallboxMeterReadings" ("ReadAt" DESC);

-- Skapa index på AccEnergy för att hitta ändringar i energiförbrukning
CREATE INDEX IF NOT EXISTS "IX_WallboxMeterReadings_AccEnergy" 
ON public."WallboxMeterReadings" ("AccEnergy" DESC);

-- Skapa composite index för att hitta mätningar inom ett tidsintervall
CREATE INDEX IF NOT EXISTS "IX_WallboxMeterReadings_ReadAt_AccEnergy" 
ON public."WallboxMeterReadings" ("ReadAt" DESC, "AccEnergy" DESC);

-- Sätt upp table comment för dokumentation
COMMENT ON TABLE public."WallboxMeterReadings" IS 
'Lagrar mätningar från Wallbox-laddaren. Innehåller energiförbrukning, effekt och mätningsdata.';

COMMENT ON COLUMN public."WallboxMeterReadings"."ReadAt" IS 
'Tidpunkt då mätningen lästes från Wallbox (UTC)';

COMMENT ON COLUMN public."WallboxMeterReadings"."RawJson" IS 
'Rådata från Wallbox-API:et i JSON-format (max 1000 tecken)';

COMMENT ON COLUMN public."WallboxMeterReadings"."AccEnergy" IS 
'Ackumulerad energiförbrukning i Wh (Watt-timmar) sedan Wallbox-installation';

COMMENT ON COLUMN public."WallboxMeterReadings"."MeterSerial" IS 
'Serienummer på elmätaren som Wallbox är kopplad till';

COMMENT ON COLUMN public."WallboxMeterReadings"."ApparentPower" IS 
'Aktuell skenbar effekt i VA (Volt-Ampere)';
