-- Script för att skapa WeatherForecasts-tabell i produktionsdatabasen
-- PostgreSQL
-- Datum: 2026-03-08
-- Beskrivning: Skapar tabell för lagring av väderprognos från SMHI

-- Skapa tabellen WeatherForecasts
CREATE TABLE IF NOT EXISTS "WeatherForecasts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Time" timestamp without time zone NOT NULL,
    "Temperature" double precision NOT NULL,
    "CloudCoverage" double precision,
    "Precipitation" double precision,
    "WindSpeed" double precision,
    "WindDirection" integer,
    "Luftfuktighet" integer,
    "Lufttryck" double precision,
    "Sikt" double precision,
    "MaxPrecipitation" double precision,
    "MeanPrecipitation" double precision,
    "WindGust" double precision,
    CONSTRAINT "PK_WeatherForecasts" PRIMARY KEY ("Id")
);

-- Skapa unik index på Time-kolumnen för att säkerställa att bara ett värde per tidpunkt lagras
CREATE UNIQUE INDEX IF NOT EXISTS "IX_WeatherForecasts_Time" ON "WeatherForecasts" ("Time");

-- Sekvens för auto-increment (alternative method)
-- CREATE SEQUENCE IF NOT EXISTS weather_forecasts_id_seq
--     START 1
--     INCREMENT 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1;
-- 
-- ALTER SEQUENCE weather_forecasts_id_seq OWNED BY "WeatherForecasts"."Id";
-- ALTER TABLE "WeatherForecasts" ALTER COLUMN "Id" SET DEFAULT nextval('weather_forecasts_id_seq'::regclass);
